language: go
sudo: false
env:
  - GO111MODULE=off
matrix:
  include:
  - os: osx
    go: 1.11.x
  - os: linux
    go: 1.11.x
notifications:
  email: false
script:
- go get -u -v github.com/go-task/task/cmd/task && task build
